// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.5.1
// source: attributes.proto

package scrapperpb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type KeyAttributes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivationDate          string    `protobuf:"bytes,1,opt,name=ActivationDate,proto3" json:"ActivationDate,omitempty"`
	DeactivationDate        string    `protobuf:"bytes,2,opt,name=DeactivationDate,proto3" json:"DeactivationDate,omitempty"`
	CompromiseDate          string    `protobuf:"bytes,3,opt,name=CompromiseDate,proto3" json:"CompromiseDate,omitempty"`
	DestroyDate             string    `protobuf:"bytes,4,opt,name=DestroyDate,proto3" json:"DestroyDate,omitempty"`
	ArchiveDate             string    `protobuf:"bytes,5,opt,name=ArchiveDate,proto3" json:"ArchiveDate,omitempty"`
	CompromiseOccuranceDate string    `protobuf:"bytes,6,opt,name=CompromiseOccuranceDate,proto3" json:"CompromiseOccuranceDate,omitempty"`
	UsageMask               int32     `protobuf:"varint,7,opt,name=UsageMask,proto3" json:"UsageMask,omitempty"`
	KeyState                KeyStates `protobuf:"varint,8,opt,name=KeyState,proto3,enum=scrapperpb.KeyStates" json:"KeyState,omitempty"`
}

func (x *KeyAttributes) Reset() {
	*x = KeyAttributes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_attributes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyAttributes) ProtoMessage() {}

func (x *KeyAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_attributes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyAttributes.ProtoReflect.Descriptor instead.
func (*KeyAttributes) Descriptor() ([]byte, []int) {
	return file_attributes_proto_rawDescGZIP(), []int{0}
}

func (x *KeyAttributes) GetActivationDate() string {
	if x != nil {
		return x.ActivationDate
	}
	return ""
}

func (x *KeyAttributes) GetDeactivationDate() string {
	if x != nil {
		return x.DeactivationDate
	}
	return ""
}

func (x *KeyAttributes) GetCompromiseDate() string {
	if x != nil {
		return x.CompromiseDate
	}
	return ""
}

func (x *KeyAttributes) GetDestroyDate() string {
	if x != nil {
		return x.DestroyDate
	}
	return ""
}

func (x *KeyAttributes) GetArchiveDate() string {
	if x != nil {
		return x.ArchiveDate
	}
	return ""
}

func (x *KeyAttributes) GetCompromiseOccuranceDate() string {
	if x != nil {
		return x.CompromiseOccuranceDate
	}
	return ""
}

func (x *KeyAttributes) GetUsageMask() int32 {
	if x != nil {
		return x.UsageMask
	}
	return 0
}

func (x *KeyAttributes) GetKeyState() KeyStates {
	if x != nil {
		return x.KeyState
	}
	return KeyStates_PRE_ACTIVE
}

type Owners struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name []string `protobuf:"bytes,1,rep,name=Name,proto3" json:"Name,omitempty"`
}

func (x *Owners) Reset() {
	*x = Owners{}
	if protoimpl.UnsafeEnabled {
		mi := &file_attributes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Owners) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Owners) ProtoMessage() {}

func (x *Owners) ProtoReflect() protoreflect.Message {
	mi := &file_attributes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Owners.ProtoReflect.Descriptor instead.
func (*Owners) Descriptor() ([]byte, []int) {
	return file_attributes_proto_rawDescGZIP(), []int{1}
}

func (x *Owners) GetName() []string {
	if x != nil {
		return x.Name
	}
	return nil
}

type KeyUsers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	UsageMask int64  `protobuf:"varint,2,opt,name=UsageMask,proto3" json:"UsageMask,omitempty"`
}

func (x *KeyUsers) Reset() {
	*x = KeyUsers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_attributes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyUsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyUsers) ProtoMessage() {}

func (x *KeyUsers) ProtoReflect() protoreflect.Message {
	mi := &file_attributes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyUsers.ProtoReflect.Descriptor instead.
func (*KeyUsers) Descriptor() ([]byte, []int) {
	return file_attributes_proto_rawDescGZIP(), []int{2}
}

func (x *KeyUsers) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KeyUsers) GetUsageMask() int64 {
	if x != nil {
		return x.UsageMask
	}
	return 0
}

var File_attributes_proto protoreflect.FileDescriptor

var file_attributes_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x73, 0x63, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x70, 0x62, 0x1a, 0x0b,
	0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xda, 0x02, 0x0a, 0x0d,
	0x4b, 0x65, 0x79, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x26, 0x0a,
	0x0e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x44, 0x61, 0x74, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x44, 0x65, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x10, 0x44, 0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74,
	0x65, 0x12, 0x26, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x6f, 0x6d, 0x69, 0x73, 0x65, 0x44,
	0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x72,
	0x6f, 0x6d, 0x69, 0x73, 0x65, 0x44, 0x61, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73,
	0x74, 0x72, 0x6f, 0x79, 0x44, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x44, 0x61, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x41,
	0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x44, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x44, 0x61, 0x74, 0x65, 0x12, 0x38, 0x0a,
	0x17, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x6f, 0x6d, 0x69, 0x73, 0x65, 0x4f, 0x63, 0x63, 0x75, 0x72,
	0x61, 0x6e, 0x63, 0x65, 0x44, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x17,
	0x43, 0x6f, 0x6d, 0x70, 0x72, 0x6f, 0x6d, 0x69, 0x73, 0x65, 0x4f, 0x63, 0x63, 0x75, 0x72, 0x61,
	0x6e, 0x63, 0x65, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x55, 0x73, 0x61, 0x67, 0x65,
	0x4d, 0x61, 0x73, 0x6b, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x55, 0x73, 0x61, 0x67,
	0x65, 0x4d, 0x61, 0x73, 0x6b, 0x12, 0x31, 0x0a, 0x08, 0x4b, 0x65, 0x79, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x73, 0x63, 0x72, 0x61, 0x70, 0x70,
	0x65, 0x72, 0x70, 0x62, 0x2e, 0x4b, 0x65, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x52, 0x08,
	0x4b, 0x65, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x1c, 0x0a, 0x06, 0x4f, 0x77, 0x6e, 0x65,
	0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x3c, 0x0a, 0x08, 0x4b, 0x65, 0x79, 0x55, 0x73, 0x65,
	0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x55, 0x73, 0x61, 0x67, 0x65, 0x4d,
	0x61, 0x73, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x55, 0x73, 0x61, 0x67, 0x65,
	0x4d, 0x61, 0x73, 0x6b, 0x42, 0x0c, 0x5a, 0x0a, 0x73, 0x63, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_attributes_proto_rawDescOnce sync.Once
	file_attributes_proto_rawDescData = file_attributes_proto_rawDesc
)

func file_attributes_proto_rawDescGZIP() []byte {
	file_attributes_proto_rawDescOnce.Do(func() {
		file_attributes_proto_rawDescData = protoimpl.X.CompressGZIP(file_attributes_proto_rawDescData)
	})
	return file_attributes_proto_rawDescData
}

var file_attributes_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_attributes_proto_goTypes = []interface{}{
	(*KeyAttributes)(nil), // 0: scrapperpb.KeyAttributes
	(*Owners)(nil),        // 1: scrapperpb.Owners
	(*KeyUsers)(nil),      // 2: scrapperpb.KeyUsers
	(KeyStates)(0),        // 3: scrapperpb.KeyStates
}
var file_attributes_proto_depIdxs = []int32{
	3, // 0: scrapperpb.KeyAttributes.KeyState:type_name -> scrapperpb.KeyStates
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_attributes_proto_init() }
func file_attributes_proto_init() {
	if File_attributes_proto != nil {
		return
	}
	file_enums_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_attributes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyAttributes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_attributes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Owners); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_attributes_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyUsers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_attributes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_attributes_proto_goTypes,
		DependencyIndexes: file_attributes_proto_depIdxs,
		MessageInfos:      file_attributes_proto_msgTypes,
	}.Build()
	File_attributes_proto = out.File
	file_attributes_proto_rawDesc = nil
	file_attributes_proto_goTypes = nil
	file_attributes_proto_depIdxs = nil
}
